include:
  - path: ./messaging.yaml
  - path: ./storages.yaml

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - "${API_PORT}:8000"
      - 5679:5678
      - 5680:5679
    command: "debugpy --listen 0.0.0.0:5678 -m uvicorn --factory application.api.main:create_app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ../app/:/app/
    networks:
      - backend
    depends_on:
      kafka:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    environment:
      MONGO_DB_CONNECTION_URI: ${MONGO_DB_CONNECTION_URI:?}
      KAFKA_URL: ${KAFKA_URL:?} 
      MONGO_DB_CHAT_DATABASE: ${MONGO_DB_CHAT_DATABASE:?}
      MONGO_DB_CHAT_COLLECTION: ${MONGO_DB_CHAT_COLLECTION:?}
      MONGO_DB_MESSAGES_COLLECTION: ${MONGO_DB_MESSAGES_COLLECTION:?}
      NEW_CHATS_EVENT_TOPIC: ${NEW_CHATS_EVENT_TOPIC:?}
      CHATS_DELETED_EVENT_TOPIC: ${CHATS_DELETED_EVENT_TOPIC:?}
      NEW_MESSAGE_RECEIVED_EVENT_TOPIC: ${NEW_MESSAGE_RECEIVED_EVENT_TOPIC:?}

networks:
  backend:
    driver: bridge