services:
  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:?}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:?}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping').ok", "--quiet"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:  
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:?}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:?}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME:?}:${MONGO_PASSWORD:?}@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - backend
      
volumes:  
  dbdata6:

networks:
  backend:
    driver: bridge