services:
  telegram-bot-consumer:
    build:
      context: ..
      dockerfile: tg_bot/Dockerfile
    container_name: telegram-bot-consumer
    command: "faststream run consumers.main:app"
    restart: always
    environment:
      TG_BOT_TOKEN: ${TG_BOT_TOKEN:?}
      WEB_API_BASE_URL: ${WEB_API_BASE_URL:?}
      KAFKA_URL: ${KAFKA_URL:?} 
      MONGO_DB_CONNECTION_URI: ${MONGO_DB_CONNECTION_URI:?}
    networks:
      - backend

networks:
  backend:
    driver: bridge