[project]
name = "dddchat"
version = "0.1.0"
description = ""
authors = [
    {name = "Robun Gid"}
]
requires-python = "^3.11"
dependencies = [
    "fastapi[httpx] (>=0.136.3,<0.137.0)",
    "motor (>=3.7.1,<4.0.0)",
    "uvicorn[all] (>=0.48.0,<0.49.0)",
    "ipython (>=9.13.0,<10.0.0)",
    "pytest (>=9.0.3,<10.0.0)",
    "faker (>=40.19.1,<41.0.0)",
    "pytest-asyncio (>=1.3.0,<2.0.0)",
    "punq (>=0.7.0,<0.8.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "pydantic-settings (>=2.14.1,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
